### ISSUE TITLE
[Bug] Paths to icons

### ISSUE THREAD

**Issue by Kristinita** [thedataking/SublimeWritingStyle#16]
### Summary

Not displayed icons in Gutter.
### Expected behavior

Icons in gutter.
### Actual behavior

![No icons in gutter](http://i.imgur.com/Wdbcaji.png)
### Steps to reproduce

I open any `txt` file → I wrote unwanted words → I not have icons in gutter.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by hstojic** [comment]
Hello, 

I get the same behavior. 

The console states "Unable to decode Packages/SublimeWritingStyle/icons/pencil-dark.png" and the issue, at least in my case, is that for some reason the path is actually Packages/Writing Style/icons. Hence, probably during the installation of the package, ST3 is instructed to use Writing Style as a directory name.

I would change the code, but I'm not sure where is the installation code?

**Comment by hstojic** [comment]
As a workaround, when I install the package manually, not through the Package control, extract the folder into "Packages" directory and name it SublimeWritingStyle, it works fine.
